### ISSUE TITLE
keyboard navigation for the forums

### ISSUE THREAD

**Issue by tracker1** [echicken/synchronet-web-v4#1]
Would be nice to include a space key event in the message reader screens to scroll by half the view height on press, unless at the bottom then move to the next message... also left/right to prev/next.

Other options might be nice too... may want to refer to the keyboard hotkeys that gmail uses as a guide.

**Comment by echicken** [comment]
Sure, I'll add some minimal keyboard navigation stuff.  I doubt if I'll go whole hog on it until I get sufficiently bored though - there's already another UI well-suited to keyboard power-users. :D

**Comment by tracker1** [comment]
I keep reaching for arrow keys (next/back) so if those were there, that would be huge for me.

**Comment by echicken** [comment]
Left and right should jump to previous and next when viewing a message thread now.  Some CSS has been added to allow for highlighting the current message.  I'll probably mess around with this a bit more; I'm not entirely satisfied with the way it works right now.

Will leave this open while I contemplate adding other shortcuts at some point in the future.

**Comment by echicken** [comment]
Heh ... note to self - stop trapping the keydown event when composing a message.  How annoying. I'll fix that tonite. :|

**Comment by tracker1** [comment]
@echicken  If your trape is in the text input box... you can use `event.stopImmediatePropagation()` to prevent the parent from seeing the event.

**Comment by echicken** [comment]
Ah right, I'm already doing that elsewhere.  Would probably be better than what I'm doing now.

**Comment by echicken** [comment]
I'm not sure why I left this issue open, but I'll close it now.  Keyboard navigation was added almost a year ago (and today I added a config toggle for it, for those who'd rather disable it).
