### ISSUE TITLE
Missing new thread in forums, fixed with minor code change

### ISSUE THREAD

**Issue by noisome** [echicken/synchronet-web-v4#10]
Line 934 for the ./lib/forum.js the m < msgBase needs to be m <= msgBase.

-        for (var m = start; m < msgBase.last_msg; m++) {
+        for (var m = start; m <= msgBase.last_msg; m++) {

**Comment by echicken** [comment]
Fixed, along with a bug that affected sorting threads from newest to oldest. (Forgot to commit this change some time ago.)
