### ISSUE TITLE
"Scambled" telnet interface

### ISSUE THREAD

**Issue by MichaelTrip1986** [echicken/synchronet-web-v4#14]
Hi,

I've pulled the last version of the v4 web interface and tried the ftelnet componenent, but the whole thing is scrambled. See attached screenshot. 

Can't figure out if this is a ftelnet problem or a web interface problem.

![image](https://user-images.githubusercontent.com/9055304/35872717-d849ab62-0b67-11e8-91f7-3ab8c5079521.png)

![image](https://user-images.githubusercontent.com/9055304/35872748-ec685aee-0b67-11e8-93fe-d649d290ef38.png)

**Comment by echicken** [comment]
There's a possibility that the problem lies within the websocket proxy; I'll see if I can reproduce the problem here and if there's anything I can do about it.  If not, it's an fTelnet thing that I can't / won't fix.

**Comment by MichaelTrip1986** [comment]
Thanks for checking it out!

**Comment by echicken** [comment]
I've dropped built-in support for fTelnet from this project.  With the exception of the 'Games' page, we're losing very little by doing this.

I recommend using the [embed wizard](http://embed-v2.ftelnet.ca/) from ftelnet.ca to generate some code that you can paste into your Home page.  This is very easy to do, will keep you using a current version of fTelnet, and saves some configuration steps.
