### ISSUE TITLE
Error: can't open /sbbs/webv4/root/index.xjs.ssjs

### ISSUE THREAD

**Issue by swulfgang** [echicken/synchronet-web-v4#16]
BBS Webpage for webv4 is located at:
http://tcb.synchronetbbs.org:4343/

Installed per installation instructions here:
https://github.com/echicken/synchronet-web-v4/wiki/Install-script-&-old-manual-installations

Completed with no error and have restarted SBBS.

When visit webpage, I get the error:
!JavaScript /sbbs/exec/xjs_handler.js line 19: Error: can't open /sbbs/webv4/root/index.xjs.ssjs: No such file or directory

**Comment by echicken** [comment]
The page that you linked to doesn't provide installation instructions.  That page is about migrating content from an older web-v4 installation over to an install-script based installation.

Installation instructions are here:
https://github.com/echicken/synchronet-web-v4/wiki/Installing-and-Updating

What is the value of the RootDirectory key in the [Web] section of your /sbbs/ctrl/sbbs.ini file?

What is the value of the web_directory key in the [web] section of your /sbbs/ctrl/modopts.ini file?

Do you have a /sbbs/webv4 directory?

Do you have a /sbbs/webv4/root directory?

**Comment by swulfgang** [comment]
What is the value of the RootDirectory key in the [Web] section of your /sbbs/ctrl/sbbs.ini file?
RootDirectory=/sbbs/webv4/root

What is the value of the web_directory key in the [web] section of your /sbbs/ctrl/modopts.ini file?
web_directory=/sbbs/webv4

Do you have a /sbbs/webv4 directory?
Yes

Do you have a /sbbs/webv4/root directory?
No, just backups bbs_utils sitemap SyncBackup SynchronetManagmentConsole SynchronetStartup

**Comment by swulfgang** [comment]
Updated my post above with the correct content.  Not sure what directory I was in before when I answered the question, so I wanted to correct it.  

I reran the script and same error.  I did have to copy unzip and place in my /sbbs/exec/ directory.  Did same with zip as I well.  Not needed for the install script but done for completeness.

**Comment by echicken** [comment]
Not sure what's going on, then.  Permissions maybe?  Did you run the install script as the same user that your BBS runs as?  Does that account have permission to write/create files in /sbbs/webv4/root?

**Comment by swulfgang** [comment]
Well, I should have thought of that.  Once I fixed it to match the rest of the /SBBS directories, problem was fixed.  I ran the install script as root and not as the bbs user.  Thank you for your help.  I will go ahead and mark this as closed.
