### ISSUE TITLE
page_ctrl is undefined

### ISSUE THREAD

**Issue by ftoledo** [echicken/synchronet-web-v4#17]
Hi! i just update cvs code of Synchronet and git pull from web-v4 and get this error

```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="icon" href="./images/favicon.ico">
		<title>
			!JavaScript  /sbbs/web/root/index.xjs.ssjs line 91: TypeError: page_ctrl is undefined

```

**Comment by echicken** [comment]
I made some changes to the structure of this application a while back.  You may find some helpful information here:

https://github.com/echicken/synchronet-web-v4/wiki/Install-script-&-old-manual-installations
