### ISSUE TITLE
Email issues

### ISSUE THREAD

**Issue by Clifra-Jones** [echicken/synchronet-web-v4#18]
Just downloaded the lastest version and have a few issues related to email.

1. Selecting email from the user dropdown threw an error.
Had to chane this line in ssbs/webv4/pages/00-mail.xjs.ssjs
load(system.exec_dir + '../web/lib/init.js');
to
load(system.exec_dir + '../webv4/lib/init.js');

2. Email from GMAIL shows allo the HTML tags when reasding email.

**Comment by echicken** [comment]
The first issue is fixed; the solution was just to remove that line; init.js is already being loaded elsewhere.

The second issue will take some more time to fix; I may get to it at some point.

(Please don't combine unrelated problem reports - open separate issues instead.  I realize that these are both email issues, but they are separate problems.  Thanks, and I appreciate the bug report.)

**Comment by echicken** [comment]
Note that to apply the fix, pages/.examples/000-mail.xjs needs to be copied up one level to the pages/ directory once it's been updated.

**Comment by echicken** [comment]
HTML issue may be fixed now (web/lib/forum.js)

**Comment by Clifra-Jones** [comment]
Thanks for the quick response. Sorry about the double issue, I'll remember that.
