### ISSUE TITLE
installer js fails win10 32bit

### ISSUE THREAD

**Issue by clintonriggs** [echicken/synchronet-web-v4#19]
unzip -uqo command does not exist on windows. I didn't see anything in the instructions, did I miss something? thx.

**Comment by echicken** [comment]
The `unzip` executable should exist in your Synchronet `exec` directory.  Can you confirm that it's there?  If it is, I'll need to make a change to this script.

**Comment by clintonriggs** [comment]
Got it, adding sbbs\exec to the system path fixed the issue.

**Comment by echicken** [comment]
Thanks for letting me know.  I made a small change to the install script which may help with this in the future.
