### ISSUE TITLE
Slow File section loading.

### ISSUE THREAD

**Issue by DaiTengu** [echicken/synchronet-web-v4#20]
I spent quite a lot of time trying to debug my issue with the File section.  My BBS (https://warensemble.com) has a HUGE file section, and displaying all the file areas (around 45 of them) takes a very long time to load. 
`Jan  2 12:05:10 bbs sbbs: web  0081 JavaScript: Done executing script: /sbbs/exec/xjs_handler.js (85.84 seconds)`

I have a total of 1,822 directories in these areas with about 200,000 files.  
I've enabled debug logging and tried to get as much information as possible, but I'm kind of at a loss.  

Each of the areas loads relatively quickly
`Jan  2 12:14:01 bbs sbbs: web  0077 JavaScript: Done executing script: /sbbs/exec/xjs_handler.js (1.46 seconds)` (This is the area with the most directories, 146.  Most others take sub .5 seconds)

Currently, I've just redirected the "files" page to the BBS's FTP site which works, but it's definitely not seamless.  I was wondering if there's anything that could be done?

**Comment by echicken** [comment]
I've been aware of this for a while.  There are some bottlenecks in the process and it's likely the only solution will be to show less detail in the library & directory listings.  Will take a look at it in the near future.

**Comment by echicken** [comment]
DaiTengu confirmed on IRC that the update sped things up by quite a bit.  Closing.
