### ISSUE TITLE
Documentation: Possibly mention privacy badger may block fTelnet

### ISSUE THREAD

**Issue by realkinetix** [echicken/synchronet-web-v4#24]
I recently switched to ecwebv4 and found that fTelnet wasn't working - FF error about the script not loading.  Took a bunch of looking around and then found that Privacy Badger was blocking fTelnet from loading as the embed-v2.ftelnet.ca site is setting cookies.  

If anyone is concerned about 3rd party sites & cookies, this may be an issue, and one may want to self-host fTelnet instead.

**Comment by echicken** [comment]
If self-hosting fTelnet solves this problem, then I'll consider making that a part of the default install.  Would rather do that than go down the road of documenting interaction with various browser plugins users may employ.

**Comment by realkinetix** [comment]
Self-hosting does resolve the issue, yes.  Totally understand your thoughts on this.

**Comment by tracker1** [comment]
@realkinetix @echicken IIRC, ftelnet is under a restrictive license (AGPL), maybe best to just have instructions on setting up ftelnet ... :-)  Also, would suggest MIT or ISC license, and added a LICENSE file to the project root for this project.

**Comment by echicken** [comment]
fTelnet won't ever be bundled in.  At best there would be a helper script to download it and set things up for self-hosting, and I would probably put that in a separate project.

Frankly I'd rather leave sysops to figure it out on their own, but the last time I ripped fTelnet support out of this project there was some griping.  It's a great program but annoying to support.

As for licensing I usually go with MIT but have no strong opinions.  I'll maybe bother to add a license to this at some point in the future.
