### ISSUE TITLE
Is line 44 of 003-games.xjs correct?

### ISSUE THREAD

**Issue by realkinetix** [echicken/synchronet-web-v4#26]
Line 44 of 003-games.xjs says:

<script>document.write('<script src="//embed-v2.ftelnet.ca/js/ftelnet-loader.norip.noxfer.js?v=' + (new Date()).getTime() + '"><\/script>');</script>

And that is exactly how it shows up when the page is rendered - from 'view source':

<script>document.write('<script src="/js/ftelnet.norip.noxfer.min.js?v=' + (new Date()).getTime() + '"><\/script>');</script>

(er, mine's a touch different since I changed some things for the local install of fTelnet)

However, is it supposed to appear rendered this way?

I tripped across this as when I go to the Games page, I get a dialog box stating "fTelnet Error: Script element with id="fTelnetScript" was not found"

That said, replacing that line with: 
<script src="/js/ftelnet.norip.noxfer.min.js?v=' + (new Date()).getTime());</script>
did not work, either, though the dialog box is no longer there, no fTelnet anything shows up on the page.

**Comment by echicken** [comment]
It looks weird but it's *almost* okay.  I think it's just missing its id attribute.

This might work:

<script>document.write('<script id="fTelnetScript" src="//embed-v2.ftelnet.ca/js/ftelnet-loader.norip.noxfer.js?v=' + (new Date()).getTime() + '"><\/script>');</script>

Or alternatively this might do:

<?xjs write('<script id="fTelnetScript" src="//embed-v2.ftelnet.ca/js/ftelnet-loader.norip.noxfer.js?v=' + (new Date()).getTime() + '"></script>'); ?>

I'm leaning toward the latter, but either way the object is to dynamically generate the timestamp portion of the query string.  If you want to try it and let me know how it goes, I can make the change.

**Comment by realkinetix** [comment]
Both suggestions work with both the remote fTelnet and the local install.

The generated code looks like:

<script id="fTelnetScript" src="/js/ftelnet.norip.noxfer.min.js?v=1559791702166"></script>

**Comment by echicken** [comment]
8ebbb7d

Applied the second proposed fix (server-side) to web/pages/.examples/003-games.xjs, should resolve this problem.
