### ISSUE TITLE
Feature request: In the Mail message list, include host information in the headers

### ISSUE THREAD

**Issue by realkinetix** [echicken/synchronet-web-v4#28]
Is this one possible?

When looking at the list of mail sitting in the mailbox, there's no information on where the mail is from, outside of the author name.  I just have netmail, so can't comment on how inbound email looks.

At any rate, it could be handy to have the FTN node info and/or other routing/host info there so, if we have to do a new mail we have that info. handy.  I expect (though haven't tried yet) that replies would do the right thing, but that information doesn't show when replying either, so I have yet to find out.

**Comment by echicken** [comment]
I believe something like "From: echicken <echicken@1:229/200>" could be added.  I'll take a look the next time I settle in to mess with this stuff.

Could also add an hidden/expandable "show more info" thing with various other bits of header information, which could provide essentially all of the (applicable) properties listed under save_msg [here](http://synchro.net/docs/jsobjs.html#MsgBase).
