### ISSUE TITLE
Feature Request:  Sub-menu Sorting

### ISSUE THREAD

**Issue by sduensin** [echicken/synchronet-web-v4#35]
I'd love to be able to "number" sub-menus to sort them.  Right now, in my menu, I have "BBS" and "Classics" drop-down sub menus...  And "Classics" should be listed first.

I really don't want to have to call it "Ze BBS!".   :-D

**Comment by echicken** [comment]
Seems like it already works this way. I am able to prefix my dropdown (and submenu) directory names like so:

pages/001-First/
pages/More/001-First/
pages/More/002-Second/

The leading numbers and hyphen are removed prior to being displayed.

The actual order in which these items are displayed will depend on the names/numbers of other files and subdirectories alongside them.

I don't think this is a new feature, but if it doesn't work on your end, an update may be in order. Let me know if it's not doing what you want and I can take a closer look.
