### ISSUE TITLE
Delete multiple emails

### ISSUE THREAD

**Issue by echicken** [echicken/synchronet-web-v4#8]
Flag multiple private messages for deletion.  Checkbox? Select all?

**Comment by l1th0** [comment]
checkbox and select all are a good idea.  Right now, you have to open each e-mail to delete them.

**Comment by echicken** [comment]
Yep, that's the reason why this will (eventually) be added.  Right now the best way to delete mail is via the terminal server (and frankly the private mail web UI is half-assed and an afterthought ATM.)

This will happen at some point, but I'll have to be pretty bored before I get to it.

**Comment by echicken** [comment]
Done.
