### ISSUE TITLE
System Info resize error

### ISSUE THREAD

**Issue by l1th0** [echicken/synchronet-web-v4#9]
When a user makes their web browser too narrow, the information on the System Information box (on the right of the screen) goes outside the cells.  In particular, the sysop, users, uptime, calls today, u/l today, etc.. are outside the cells.  Tested in Mozilla Firefox and I.E. 11.  Synchronet oneliners plugin has same issue.

**Comment by echicken** [comment]
I can see slight text-overflow problems when the browser is very narrow (on the verge of collapsing into the mobile view) but can't reproduce a lot of content being outside of the sidebar border.  What Firefox version, and can I assume it's on Windows?  If you want to attach a screenshot, that might give me a better understanding.

**Comment by l1th0** [comment]
Yes, I'm using Windows 7 with Firefox is 50.1.0 and I.E. 11. Appears to be only the text in the grey cells. Attached is a sample screenshot.

![sysinfoerror](https://cloud.githubusercontent.com/assets/24970032/21739569/44f92dea-d45b-11e6-94a2-f3d4ff65cc62.jpg)

**Comment by echicken** [comment]
Okay - if you want to update and give it a shot, I just committed a change to web/root/css/style.css which should help.  Here's what it looks like for me now with the browser window at about 770px width:

![image](https://cloud.githubusercontent.com/assets/3680368/21743387/135fedfe-d4cf-11e6-93b2-18b94b86e9ee.png)

Let me know if that works for you.

**Comment by l1th0** [comment]
Looks like it's fixed!  Tried it again in I.E. 11 and Firefox.  There's no more text overflow in the grey cells.
